### PR TITLE
Better character controller

### PR DESCRIPTION
**Pull request by psychoFungus**
Issue #52

- Changed map collider to composite
- Removed floating collider system
- Some bugfixes in enemySpawner to match new map collider

### CODE REVIEW

**Comment by Brim7Premium** [comment]
is the new method as smooth as the old floating capsule method?

**Comment by psychoFungus** [comment]
Yes

**Comment by Brim7Premium** [comment]
After walking for literally 3 seconds, I have determined that the best system for us to use is the floating capsule. There really isn't a way it seems to get a smooth movement system like the one we had without a floating capsule. The new one has little imperfections (and some big problems) that make it feel bugged and incomplete. The old system was basically perfect minus not working on low framerates. I guess I'm asking if you can just figure out why it doesn't work on low framerates and fix it. By fix it, I don't mean completely change it, I mean just fix the one problem that it had.

**Comment by psychoFungus** [comment]
Not only. Besides some minor bugs with slopes and steps, there's a bigger issue. As I understand whole point of boss battles would be precision of movement, similar to terraria calamity. Purpose of this system is to smooth out player vertical movement, which leads to quite noticable oscillation after falling.
Also can you be a little more specific about what you don't like? I have basically no idea what you are blaming. If this acceleration and deacceleration or some problems with animation, don't look at it, this is fixable just by adjusting numbers.
I think this taking a bit too long.  Do you want me to continue working on alternative movement systems or leave floating capsule system as it is and do something else? I don't know how to fix floating capsule system, if possible at all, without creating bigger issue and not rewriting the whole thing.

**Comment by Brim7Premium** [comment]
For now, just use the already existing floating capsule system. Also, if you ever plan to add these changes to main, make sure to document every change made and why (all the readme rules)

**Pull request merged**
