### PR TITLE
Rework of base classes

### PR DESCRIPTION
**Pull request by psychoFungus**
- Code optimization
- Switched to rb.velocity instead of UpdateVelocity
- Entities will die using built-in methods and use corresponding callbacks
- Changed NewProjectile method
- Changed projectiles and entities to match changes

### CODE REVIEW

**Comment by Brim7Premium** [comment]
@psychoFungus Just let me know when I can merge it for testing

**Comment by psychoFungus** [comment]
Fixing all issues will take some time, so I need to be sure that these changes satisfy everyone.

**Comment by psychoFungus** [comment]
Also, it is better to make all universal additions at this point, because later it will take much more time to implement.

**Comment by Brim7Premium** [comment]
@psychoFungus any updates of this? I'm waiting to work on my end of the project until this is done

**Comment by psychoFungus** [comment]
Basically work is done, I'll tell you when I polish everything.

**Comment by psychoFungus** [comment]
@Brim7Premium you can merge

**Pull request merged**
